name: party_potion
description: A new Flutter project.
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.3.0
  device_preview: ^1.1.0
  url_launcher: ^6.1.7
  bloc: ^8.1.1
  cloud_firestore: ^5.2.0
  meta: ^1.8.0
  flutter_bloc: ^8.1.2
  firebase_auth: ^5.1.3
  dio: ^5.5.0+1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  retrofit: ^4.1.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  retrofit_generator: ^8.1.2
  injectable_generator: ^2.1.5
  mocktail: ^1.0.4
  bloc_test: ^9.1.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
    
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/alcohols_icon/
